# A reasonable number to start with
num_particles: 200

lidar_scale_to_map_scale: 5.0 #1.0 for 2D racecar sim 5.0 for TESSE

# The number of lidar beams emitted from
# each particle. This doesn't need to be
# equal to the actual number (>1000)
# so long as you downsample properly
num_beams_per_particle: 100

# The field of view centered around theta=0
scan_field_of_view: 4.71 # radians

# Discretize the theta space for faster ray tracing
scan_theta_discretization: 500

# The names of topics to listen and publish to
map_topic: "/map"

# scan_topic: "/tesse/front_lidar/scan" #"/scan" for rviz "/tesse/front_lidar/scan" for tesse
# odom_topic: "/tesse/odom" #"/odom" for rviz, "/tesse/odom" for ground_truth odom

scan_topic: "/scan"
odom_topic: "/odom"
# /tesse/odom/noisy for motion model

# The frame you should publish your transform to
# particle_filter_frame: "/hood/lidar"

particle_filter_frame: /base_link_pf #for rviz /hood/lidar for TESSE

# Deterministic flag; set to true to remove all added noise
deterministic: False
